### PR TITLE
change network_interface to instance in aws_eip resource

### PR DESCRIPTION
**Pull request by ByJacob**
## what
* Change network_interfface to instance in aws_eip

## why
* Unable to modify the network interface while the instance is in 'terminate' state

## references
*  #95

### CODE REVIEW

**Comment by ByJacob** [comment]
Error in terratest is related with https://github.com/cloudposse/terraform-aws-security-group/issues/13

**Comment by ByJacob** [comment]
PING :)

**Comment by aknysh** [comment]
@ByJacob  thanks, LGTM
Can you please run

```
make init
make github/init
make readme
```

to update the GitHub actions to the latest versions?

**Review by aknysh — APPROVED** [review]
thanks @ByJacob

**Comment by ByJacob** [comment]
No problem. I often have some non-standard use cases and try to correct it in my spare time :)

**Pull request merged**
