### PR TITLE
Fix broken public_ip output

### PR DESCRIPTION
**Pull request by maartenvanderhoef**
## What
Changing the handling of the `public_ip`-output to use concat instead of coalesce

## Why
Coalesce breaks with 0.12 when the resource returns an empty tuple.

### CODE REVIEW

**Comment by rsrchboy** [comment]
Gah, I've been hitting this a lot.  Any chance we can rebase this?  I'm happy to submit a new PR with these changes  + readme updates.

**Comment by maximmi** [comment]
closed in #54

**Pull request closed without merging**
