### PR TITLE
Do not set iops and throughput for non-supporting volume types

### LINKED ISSUE #137: ebs_throughput default value is out of range
When using 0.44.0 I get 
`│ Error: expected throughput to be in the range (125 - 1000), got 0
│ 
│   with module.instance.aws_ebs_volume.default[0],
│   on .terraform/modules/instance/main.tf line 178, in resource "aws_ebs_volume" "default":
│  178:   throughput        = local.ebs_throughput
`
the issue is caused by the ebs_throughput default which is set to 0 but it needs to be between 125 and 1000 i.e. 

`ebs_throughput         = var.ebs_volume_type == "gp3" ? var.ebs_throughput : "0"`
should be for example
`ebs_throughput         = var.ebs_volume_type == "gp3" ? var.ebs_throughput : "125"`

### PR DESCRIPTION
**Pull request by cinacio**
## what
* Only set iops and throughput arguments for volume types supporting those options.

## why
* According to the documentation for the [aws_ebs_volume resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ebs_volume), the `iops` argument is only valid for volumes types `io1`, `io2` & `gp3`.
* According to the same documentation, the `throughput` argument is only valid for volume type `gp3`.
* Setting the throughput of a `gp2` volume to "0" triggers the following error

>  Error: expected throughput to be in the range (125 - 1000), got 0
>
>   with module.instance.aws_ebs_volume.default[0],
>   on .terraform/modules/instance/main.tf line 178, in resource "aws_ebs_volume" "default":
>  178:   throughput        = local.ebs_throughput

## references 
* closes #137

### CODE REVIEW

**Comment by cinacio** [comment]
Hi @dotCipher @RothAndrew,

Is there anything wrong with this PR? Do I need to do something in order for it to be reviewed?

**Comment by cinacio** [comment]
@RothAndrew @dotCipher Can I do anything to help you guys get a quick look at this?

**Review by RothAndrew — DISMISSED** [review]
LGTM, changes make sense to me.

**Comment by RothAndrew** [comment]
@aknysh is this okay to merge even though `auto-format` is failing? I'm seeing that it is not set as required.

**Comment by jamengual** [comment]
@cinacio can you run ```
make init
make github/init
```

**Comment by topikachu** [comment]
I meet error
`expected throughput to be in the range (125 - 1000), got 0`

Can anybody merge and release this fix?

**Review by nitrocode — APPROVED** [review]

**Pull request merged**
