### PR TITLE
Add ability to configure instance tenancy

### LINKED ISSUE #139: Support configuration of instance tenancy
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[Slack Community](https://slack.cloudposse.com)

## Describe the Feature

I'd like the ability to use this module to create an instance using `tenancy` other than the default.

## Expected Behavior

If I set `tenancy = "dedicated"` (for example), it will create the instance using dedicated tenancy instead of default (shared) tenancy.

## Use Case

An organization that I work with has a security policy that requires use of dedicated tenancy.

## Describe Ideal Solution

A new variable `tenancy` is available that allows me to set any of the accepted values, which are `default`, `dedicated`, or `host`. See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#tenancy

## Alternatives Considered

Use a different module

### PR DESCRIPTION
**Pull request by RothAndrew**
## what
* Add new variable `tenancy` that allows user to configure instance tenancy (`default` (default), `dedicated`, or `host`)

## why
* An organization that I work with has a security policy that requires use of dedicated tenancy. This PR adds the capability to do that when using this module.

## references
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#tenancy
* Closes #139

### CODE REVIEW

**Comment by RothAndrew** [comment]
Looks like the pipeline runs are failing on "Update GitHub Status for pending".

https://github.com/cloudposse/actions/actions/runs/3145776764/jobs/5113473987

**Review by Nuru — DISMISSED** [review]
Thank you for the contribution.

Since `tenancy` is a string input but only has 3 valid values (really should be an `enum` but Terraform does not support them), please add a validation rule for it.

**Comment by RothAndrew** [comment]
Will do, thanks 😄

**Comment by RothAndrew** [comment]
@Nuru done, PTAL

**Comment by RothAndrew** [comment]
bump @Nuru PTAL

**Review by jamengual — APPROVED** [review]

**Review by Gowiem — APPROVED** [review]
LGTM

**Pull request merged**
