### PR TITLE
allow assigning instance to a capacity reservation id

### PR DESCRIPTION
**Pull request by joelsdc**
## what
* allow assigning instance to a capacity reservation id

## why
* When using capacity reservations for certain EC2 instances, you need to specify the capacity id at launch to assign it.

## references
* See: https://github.com/cloudposse/terraform-aws-ec2-instance/issues/120

### CODE REVIEW

**Comment by joelsdc** [comment]
This is a very simple change. As it involves adding a new config option, where should I add it?

**Comment by Gowiem** [comment]
@joelsdc can you open this PR under your personal GH account OR allow Cloud Posse access to the fork you made? Our auto-format CI is failing as it cannot access your fork right now:

```
  Initialized empty Git repository in /__w/terraform-aws-ec2-instance/terraform-aws-ec2-instance/.git/
  /usr/bin/git remote add origin https://github.com/TRIPP-Inc/terraform-aws-ec2-instance
  Error: fatal: unsafe repository ('/__w/terraform-aws-ec2-instance/terraform-aws-ec2-instance' is owned by someone else)
  To add an exception for this directory, call:
```

**Comment by joelsdc** [comment]
Hi guys, sorry for the delay! 

I wasn't sure what is the correct user / team to add with write access, so I added the following two:

image


Let me know if you need anything else from our end.

Thanks!

**Comment by joelsdc** [comment]
Regarding the conflicts: I can't see the logs (probably due to the time since I opened this PR until now that I've got some cycles for this).

Can you re-run the `/test all` so I can see what is wrong and fix it?

Thanks!

**Pull request closed without merging**
