### PR TITLE
feat(aws_instance): conditional IAM instance profile

### PR DESCRIPTION
**Pull request by haidargit**
## what
This PR enables a conditional _[iam_instance_profile](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#iam_instance_profile)_ variable for the ec2 module.

## why
This feature request offers users the flexibility to decide whether to associate an IAM instance profile with their instances.

## references
- closes feature request #180 

Kindly review this PR for module improvements. Thank you

### CODE REVIEW

**Comment by haidargit** [comment]
Hi @kevcube , @nitrocode 
would you help to review the PR or any other changes that need to be added?

Thank you

**Comment by nitrocode** [comment]
Did you try setting the `instance_profile` to an empty string to disable its creation without an additional flag?

**Comment by haidargit** [comment]
which additional flag do you mean, @nitrocode ?
could you help comment or point to the code/PR?

Thanks 🙌

**Comment by joe-niland** [comment]
@nitrocode `instance_profile == ""` signifies that the default instance profile and role should be created, whereas #180 is requesting that it be possible to create an instance without a profile + role.

**Comment by haidargit** [comment]
Thank you, yes that's what I meant for this feature request. @joe-niland , @nitrocode

**Comment by joe-niland** [comment]
Hi @haidargit please have a look at the Terratest failures: https://github.com/cloudposse/actions/actions/runs/7605926145/job/20710921759

**Comment by haidargit** [comment]
okay @joe-niland, i am checking on it

**Comment by haidargit** [comment]
i have committed the changes for applying the consistent types for the true and false result expressions to these two outputs

`output "role"` & `output "role_arn"`

could you help test again @joe-niland ?
Thanks!

**Comment by joe-niland** [comment]
@haidargit all seems fine. I will just make sure @nitrocode is OK with the PR as well before we proceed.

**Review by joe-niland — APPROVED** [review]

**Comment by nitrocode** [comment]
I defer to you folks. Thanks for including me. :)

**Comment by joe-niland** [comment]
Cheers @nitrocode!

Thanks for your contribution @haidargit !

**Comment by haidargit** [comment]
your welcome @joe-niland, @joe-niland  👍🏻 👍🏻

**Pull request merged**
